### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by sokol07** [OpenScan-org/OpenScan-ML#1]
Hi,
please activate the discussions module for this repository so we could discuss your idea. 
I have some thoughts but I think writing them down in a discussion would be more suitable than in an "issue".

**Comment by sokol07** [comment]
@OpenScanEu bump of the topic - I guess we could push this topic a bit, this is quite an interesting idea, I'd love to so where this goes.

**Comment by OpenScanEu** [comment]
I hope to be able to spend some more time on this idea in the near future. I think, I will give the following a try: [perceptilabs](https://www.perceptilabs.com/). This is quite a visual approach, but you can also see the underlying code. 
I just need to finalize the labels of the dataset... ^^
Edit: I totally forgot to activate the discussion module, but did so now :)
